[general]
log_level=4
log_to_syslog=true

[postgresql]
dsn="postgres://chirpstack_ns:chirpstack_ns@localhost/chirpstack_ns?sslmode=disable"

[network_server]
net_id="000000"

  [network_server.band]
  name="AS923"

  [[network_server.network_settings.extra_channels]]
  frequency=923600000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=923800000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=924000000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=924200000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=924400000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=924600000
  min_dr=0
  max_dr=5
